// GENERATED by @edgedb/generate v0.5.6

import type { Executor } from 'edgedb';

export type DeleteNotificationTokenArgs = {
  readonly token: string;
  readonly tournamentId: string;
};

export type DeleteNotificationTokenReturns = {
  id: string;
} | null;

export function deleteNotificationToken(
  client: Executor,
  args: DeleteNotificationTokenArgs
): Promise<DeleteNotificationTokenReturns> {
  return client.querySingle(
    `\
DELETE
    NotificationToken
FILTER
    .token = <str>$token
    AND .tournamentId = <str>$tournamentId`,
    args
  );
}
