// GENERATED by @edgedb/generate v0.5.6

import type { Executor } from 'edgedb';

export type GetNotificationTokensArgs = {
  readonly tournamentId: string;
};

export type GetNotificationTokensReturns = Array<{
  token: string;
}>;

export function getNotificationTokens(
  client: Executor,
  args: GetNotificationTokensArgs
): Promise<GetNotificationTokensReturns> {
  return client.query(
    `\
SELECT 
    NotificationToken {
        token
    }
FILTER 
    .tournamentId = <str>$tournamentId`,
    args
  );
}
