// GENERATED by @edgedb/generate v0.5.6

import type { Executor } from 'edgedb';

export type CreateNotificationTokenArgs = {
  readonly token: string;
  readonly tournamentId: string;
  readonly email: string;
};

export type CreateNotificationTokenReturns = {
  id: string;
};

export function createNotificationToken(
  client: Executor,
  args: CreateNotificationTokenArgs
): Promise<CreateNotificationTokenReturns> {
  return client.queryRequiredSingle(
    `\
INSERT NotificationToken {
  token := <str>$token,
  tournamentId := <str>$tournamentId,
  user := (SELECT User FILTER .email = <str>$email LIMIT 1)
};`,
    args
  );
}
