// GENERATED by @edgedb/generate v0.5.6

import type { Executor } from 'edgedb';

export type CreateFeedbackArgs = {
  readonly description: string;
};

export type CreateFeedbackReturns = {
  id: string;
};

export function createFeedback(
  client: Executor,
  args: CreateFeedbackArgs
): Promise<CreateFeedbackReturns> {
  return client.queryRequiredSingle(
    `\
insert Feedback {
  description := <str>$description,
}`,
    args
  );
}
